<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/5/9
 * Time: 10:33
 */

namespace core\wen\exception;


use Throwable;

abstract class AbstractException extends \Exception
{
    public function __construct($message = "", $code = 0, Throwable $previous = null)
    {
//        echo '<div style="background: black;color: yellow;padding: 0px 10px 20px; ">';
        parent::__construct($message, $code, $previous);
    }


    public function __wakeup()
    {
        parent::__wakeup(); // TODO: Change the autogenerated stub
//        echo '</div>';
    }

}